config/routes.rb
Rails.application.routes.draw do

  get 'begin', to: 'pages#begin'
  get 'news', to: 'pages#news'
  get 'material', to: 'pages#material'

  namespace :site do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end

  namespace :users_backoffice do
    get   'welcome/index'
    get   'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get   'list_questions', to: 'questions#list_questions', as: 'list_questions'
    get   'zip_code', to: 'zip_code#show'
    resources :languages, only: [:show]
    resources :questions, only: [:show]
  end

  namespace :admins_backoffice do
    get 'welcome/index'  # Dashboard
    resources :admins    # Administradores
    resources :users     # Usuários
    resources :subjects  # Assuntos/Áreas
    resources :questions # Perguntas
    resources :languages # Linguagens
    resources :ranking, only: [:index]
  end

  devise_for :users
  devise_for :admins, skip: [:registrations]

  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'pages#begin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions

  has_many :answers, dependent: :destroy
  has_many :answer_attempts, dependent: :destroy

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  #Callback
  after_create :set_statistic

  # Kaminari
  paginates_per 5

  # Scopes
  scope :answered_by_user, -> (user) {
    joins(:answer_attempts).where('answer_attempts.user_id = ?', user.id)
  }

  scope :not_answered_by_user, -> (user) {
    if user
      joins("LEFT JOIN answer_attempts ON (answer_attempts.question_id = questions.id AND answer_attempts.user_id = #{user.id})").
        where('answer_attempts.id IS NULL').
        group('questions.id')
    else
      all
    end
  }

  scope :_search_subject_, ->(page, subject_id) {
    includes(:answers, :subject).where(subject_id: subject_id).page(page)
  }

  scope :_search_, ->(page, term) {
    includes(:answers, :subject).where('lower(description) LIKE ?', "%#{term.downcase}%").page(page)
  }

  scope :last_questions, ->(page) {
    includes(:answers).order('RANDOM()').page(page)
  }

  def self.number_of_questions_anwered_by_user(user)
    answered_by_user(user).length
  end

  def self.number_of_questions_not_anwered_by_user(user)
    not_answered_by_user(user).length
  end

  private

  def set_statistic
    AdminStatistic.set_event(AdminStatistic::EVENTS[:total_questions])
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
     before_action :set_question, only: %i[edit update destroy]
     before_action :get_subjects, only: %i[new edit]

  def index
    respond_to do |format|
      format.html { @questions = Question.includes(:subject).page(params[:page]) }
      format.pdf  { @questions = Question.includes(:subject) }
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: 'Questão cadastrada com sucesso!'
    else
    render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: 'Questão atualizada com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description,
                                      :subject_id,
                                      answers_attributes: %i[id description correct _destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/users_backoffice/profile_controller.rb
class UsersBackoffice::ProfileController < UsersBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_user

  def edit
    @user.build_user_profile if @user.user_profile.blank?
  end

  def update
    if @user.update(params_user)
      bypass_sign_in(@user)
      unless params_user[:user_profile_attributes][:avatar]
        redirect_to users_backoffice_profile_path, notice: "Usuário Atualizado com Sucesso"
      end
    else
      render :edit
    end
  end

    private

  def set_user
    @user = User.find(current_user.id)
  end

  def params_user
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
    user_profile_attributes: [:id, :zip_code, :address, :gender, :birthdate, :avatar])
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/users_backoffice/questions_controller.rb
module UsersBackoffice
  class QuestionsController < UsersBackofficeController
    def list_questions
      @languages = Language.all
    end

    def show
      @question = Question.find(params[:id])
      set_previous_and_next_questions
    end

    private

    def set_previous_and_next_questions
      subject = @question.subject
      questions = subject.questions
                         .not_answered_by_user(current_user)
                         .where
                         .not(id: @question.id)
                         .to_a

      questions.delete(@question)
      questions.shuffle!

      if questions.length >= 1
        @next_question = questions.first
      else
        @next_question = nil
      end
    end
  end
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
    @user_statistic = UserStatistic.find_or_create_by(user: current_user)
    @questions = Question.all
  end
end

app/controllers/users_backoffice/zip_code_controller.rb
class UsersBackoffice::ZipCodeController < UsersBackofficeController
  def show
    @cep = CEP.new(params[:zip_code])
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :build_profile
  layout 'users_backoffice'

  private

  def build_profile
    current_user.build_user_profile if current_user.user_profile.blank?
  end

  def list_questions
    @languages = Language.all
  end

  def show
    @language = Language.find(params[:id])
  end

end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/users_backoffice/profile_helper.rb
module UsersBackoffice::ProfileHelper
    def gender_select(user, current_gender)
        user.user_profile.gender == current_gender ? 'btn-primary' : 'btn-default'
    end
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice/zip_code_helper.rb
module UsersBackoffice::ZipCodeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
    def avatar_url
      avatar = current_user.user_profile.avatar
      avatar.attached? ? avatar : 'images.png'
    end
end

app/views/users_backoffice/questions/list_questions.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Listagem de Perguntas por tópico</title>
    <style>
        h1 {
            font-size: 38px;
            color: black;
            font-weight: bold;
            margin-bottom: 40px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
            border: 2px solid orange;
            padding: 5px 10px;
            display: inline-block;
        }

        .language-link {
            font-size: 24px;
            color: black;
            text-decoration: none;
            font-weight: bold;
        }

        .subject-link {
            font-size: 18px;
            color: blue;
            text-decoration: none;
        }

        .separator {
            border-top: 1px solid #ccc;
            margin: 20px 0;
        }

        .subjects ul li a {
            color: black;
        }
    </style>
</head>
<body>

    <h1>Listagem de Perguntas por tópico</h1>

    <% @languages.each do |language| %>
        <div class="language">
            <h2>
                <%= link_to "#{language.language_name} (#{language.subjects.count} assuntos)", users_backoffice_language_path(language), class: 'language-link' %>
            </h2>

            <div class="subjects" style="display: none;">
                <% language.subjects.each do |subject| %>
                    <h3>
                        <%= link_to "#{subject.description} (#{subject.questions.not_answered_by_user(current_user).length} questões)", '#', class: 'subject-link' %>
                    </h3>

                    <ul style="display: none;">
                        <% subject.questions.not_answered_by_user(current_user).each do |question| %>
                            <li>
                                <%= link_to question.description, users_backoffice_question_path(question) %>
                            </li>
                        <% end %>
                    </ul>
                <% end %>
            </div>
        </div>

        <div class="separator"></div>
    <% end %>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const languageLinks = document.querySelectorAll('.language-link');
            const subjectLinks = document.querySelectorAll('.subject-link');

            languageLinks.forEach(link => {
                link.addEventListener('click', function(event) {
                    event.preventDefault();
                    const subjectsDiv = this.parentNode.nextElementSibling;
                    toggleDisplay(subjectsDiv);
                });
            });

            subjectLinks.forEach(link => {
                link.addEventListener('click', function(event) {
                    event.preventDefault();
                    const questionsList = this.parentNode.nextElementSibling;
                    toggleDisplay(questionsList);
                });
            });

            function toggleDisplay(element) {
                if (element.style.display === 'none') {
                    element.style.display = 'block';
                } else {
                    element.style.display = 'none';
                }
            }
        });
    </script>
</body>
</html>

app/views/users_backoffice/questions/show.html.erb
<div style="position: absolute; top: 90px; right: 10px;">
  <button type="button" class="btn btn-default btn-circle">
    <i class="fa fa-undo"></i>
    <%= link_to users_backoffice_list_questions_path, style: "margin-left: 10px;" do %>
      Voltar à Lista de Questões
    <% end %>
  </button>
</div>

<p style="color: black;"><strong><%= @question.subject.description %> (<%= @question.subject.questions.not_answered_by_user(current_user).length %> questões)</strong></p>
<h3 style="margin-top: 20px; color: blue;"><%= @question.description %></h3>

<style>
.colored-hr {
    border-top: 2px solid blue;
}

.fixed-buttons {
    position: fixed;
    bottom: 10px;
    right: 10px;
  }
</style>

<div class="colored-hr"></div>
<div style="margin-top: 20px;">
  <%= form_with url: site_answer_path do |form| %>
    <% @question.answers.each do |answer| %>
      <li style="list-style:none;">
        <div class="radio">
          <label>
            <%= radio_button_tag 'answer_id', answer.id %>
            <p style="color: black;"><%= answer.description %></p>
          </label>
        </div>
      </li>
    <% end %>
</div>
<li style="list-style:none;">
<% if user_signed_in? %>
  <%= form.submit "Responder", class: "btn btn-default", id: "submit_#{@question.id}", style:"margin-top: 20px;" %>
<% end %>
<% end %>

  <div class="fixed-buttons">
      <% if @next_question.present? %>
        <button type="button" class="btn btn-default btn-circle">
          <%= link_to 'Próxima Questão', users_backoffice_question_path(@next_question) %>
          <i class="fa fa-caret-right"></i>
        </button>
      <% else %>
        <% if @question.present? %>
        <div class="alert alert-info" role="alert">
          Essa é a última pergunta desse assunto. Responda e volte para a página anterior!
        </div>
        <% end %>
      <% end %>
  </div>